return {
  "notomo/assertlib.nvim/lua/assertlib/asserter.lua",
  "notomo/assertlib.nvim/lua/assertlib/function/buffer.lua",
  "notomo/assertlib.nvim/lua/assertlib/function/cursor.lua",
  "notomo/assertlib.nvim/lua/assertlib/function/list.lua",
  "notomo/assertlib.nvim/lua/assertlib/function/message.lua",
  "notomo/assertlib.nvim/lua/assertlib/function/mode.lua",
  "notomo/assertlib.nvim/lua/assertlib/function/tab.lua",
  "notomo/assertlib.nvim/lua/assertlib/function/window.lua",
  "notomo/assertlib.nvim/lua/assertlib/init.lua",
  "notomo/misclib.nvim/lua/misclib/error_handler.lua",
  "notomo/misclib.nvim/lua/misclib/highlight.lua",
  "notomo/misclib.nvim/lua/misclib/message.lua",
  "notomo/misclib.nvim/lua/misclib/test/assert.lua",
}
